In [27]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [28]:
hr_data = pd.read_csv('HR_comma_sep.csv')

In [29]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [30]:
hr_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   sales                  14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [31]:
hr_data.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

In [32]:
hr_data.shape

(14999, 10)

In [33]:
hr_data.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
sales                    0
salary                   0
dtype: int64

In [34]:
hr_data['salary'].value_counts()

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [35]:
hr_data['sales'].value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: sales, dtype: int64

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
encoder = LabelEncoder()

In [38]:
hr_data['salary'] = encoder.fit_transform(hr_data['salary'])

In [39]:
hr_data['sales'] = encoder.fit_transform(hr_data['sales'])

In [40]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0      7   
1                   6              0     1                      0      7   
2                   4              0     1                      0      7   
3                   5              0     1                      0      7   
4                   3              0     1                      0      7   

   salary  
0       1  
1       2  
2       2  
3       1  
4       1

In [41]:
hr_data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years  sales  salary  
0                          0      7       1  
1                          0      7       2  
2                          0      7       2  
3                          0      7       1  
4                          0      7       1  
...                      ...    ...     ...  
14994                      0      8       1  
14995                      0      8       1  
14996                      0      8       1  
14997                      0      8       1  
14998                      0      8       1  

[14999 rows x 10 columns]

In [44]:
X = hr_data.loc[:, ['satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company','sales']].values #when we call .values we convert the dataframe to arrys usually 2-d
Y = hr_data.iloc[:, 9].values

In [45]:
X

array([[3.80e-01, 5.30e-01, 2.00e+00, 1.57e+02, 3.00e+00, 7.00e+00],
       [8.00e-01, 8.60e-01, 5.00e+00, 2.62e+02, 6.00e+00, 7.00e+00],
       [1.10e-01, 8.80e-01, 7.00e+00, 2.72e+02, 4.00e+00, 7.00e+00],
       ...,
       [3.70e-01, 5.30e-01, 2.00e+00, 1.43e+02, 3.00e+00, 8.00e+00],
       [1.10e-01, 9.60e-01, 6.00e+00, 2.80e+02, 4.00e+00, 8.00e+00],
       [3.70e-01, 5.20e-01, 2.00e+00, 1.58e+02, 3.00e+00, 8.00e+00]])

In [46]:
Y

array([1, 2, 2, ..., 1, 1, 1])

In [47]:
from sklearn.preprocessing import StandardScaler 

In [48]:
sc = StandardScaler()
x_scaler = sc.fit_transform(X)


In [49]:
x_scaler

array([[-0.93649469, -1.08727529, -1.46286291, -0.88203988, -0.34123516,
         0.39372503],
       [ 0.75281433,  0.84070693,  0.97111292,  1.22042276,  1.71343614,
         0.39372503],
       [-2.02247906,  0.95755433,  2.59376348,  1.4206573 ,  0.34365527,
         0.39372503],
       ...,
       [-0.97671633, -1.08727529, -1.46286291, -1.16236823, -0.34123516,
         0.74231612],
       [-2.02247906,  1.42494396,  1.7824382 ,  1.58084493,  0.34365527,
         0.74231612],
       [-0.97671633, -1.14569899, -1.46286291, -0.86201642, -0.34123516,
         0.74231612]])

In [50]:
from sklearn.decomposition import PCA #breaking down 

In [51]:
pca = PCA(n_components = 3)

p = pca.fit_transform(x_scaler)

In [52]:
p

array([[-1.90614101,  0.94608855, -0.52451848],
       [ 2.13259771, -0.35755774, -0.15935961],
       [ 3.05404332,  1.51246206, -0.72382247],
       ...,
       [-2.05429567,  0.97668661, -0.87207256],
       [ 2.91169878,  1.19415868, -1.01071863],
       [-1.91896286,  0.96080547, -0.87622168]])

In [55]:
principalDF = pd.DataFrame(data=p, columns= ['PC1', 'PC2','PC3'])
finalDf = pd.concat([principalDF, hr_data[['salary']]], axis = 1)
finalDf.head()

PC1       PC2       PC3  salary
0 -1.906141  0.946089 -0.524518       1
1  2.132598 -0.357558 -0.159360       2
2  3.054043  1.512462 -0.723822       2
3  1.546991 -0.280105 -0.251770       1
4 -1.910297  0.995700 -0.532968       1